### ISSUE TITLE
Research Kenya/Ethiopia SMS gateways

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#1]
STP uses Infobit, which covers both Eth/Ken: http://www.infobip.com/

**Comment by niryariv** [comment]
@bnedavies since currently we're thinking the STP will be our SMS sending tool, I suppose we can put this aside for now and continue using infobip - makes sense?

**Comment by bnedavies** [comment]
We can set it aside for now for Kenya, but we will need to still research what will work in Ethiopia - the STP is only setup for Kenya at the moment...will infobip work in Ethiopia?

**Comment by amosgichamba** [comment]
The gateway we are using is global and submits SMSes anywhere in the world.
It will definitely work for Ethiopia. Nir and team, let me know if you need
me to allow sending messages to Ethiopia.

**Comment by niryariv** [comment]
we'll be using the STP for the gateway, closing for now
