### ISSUE TITLE
pull the RSS feed from the blog into the LAST UPDATES "news" tab

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#100]
http://livestockinsurance.wordpress.com/feed/

**Comment by niryariv** [comment]
doesn't seem to be implemented - can u check?

![screen shot 2014-09-21 at 4 19 30 pm](https://cloud.githubusercontent.com/assets/1771/4348570/f28d4da6-4191-11e4-84a6-94b5bc2a0e36.png)

**Comment by Moo64c** [comment]
@niryariv this is implemented in a PR Dudi still marks as WIP, and I see it's not yet merged to the http://dev-ibli.gotpantheon.com/ site.

Right now there's a default placeholder plugin still in effect, and the two or three modules in the site aren't even uploaded there. Did @DavidGizra  finish working on this? We'd need to rebuild the site after this PR (new contrib modules "feeds" and "job scheduler") from what I'm understanding here

**Comment by niryariv** [comment]
the site is still dev only, no problem if u need to rebuild. check the existing code, if it works just go ahead & merge

**Comment by Moo64c** [comment]
Rebuilding this locally seems to take the site a few versions back and it the feed isn't working (at least locally) you should ask Dudi to see what's going on with it. (also this can't be merged) I'm not familiar enough with the site to say I can do that merge without breaking anything.

**Comment by niryariv** [comment]
the code changed a lot since Dudi worked on it - feel free to go ahead and reimplement from scratch.

**Comment by niryariv** [comment]
@nader77 can u check?

**Comment by nedSaf** [comment]
Ok on it.

**Comment by niryariv** [comment]
done
