### ISSUE TITLE
add Ethiopia to the map

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#101]
There are 10 regions in Ethiopia which we'll add the map:
- [ ] replace the current GeoJSON with [this](https://github.com/Gizra/IBLI/blob/master/dataProcessing/Ethiopia/iblimatlab/Ken%2BEthShapefile/Ken%2BEth/KenyaEthiopia_IBLIunits_May2014.geojson) Kenya + Ethiopia one.
- [ ] add the Ethiopian index data: [SRSD15](https://github.com/Gizra/IBLI/blob/master/dataProcessing/Ethiopia/iblimatlab/OutCurrentIndex/SRSD15indem.csv) and [LRLD15](https://github.com/Gizra/IBLI/blob/master/dataProcessing/Ethiopia/iblimatlab/OutCurrentIndex/LRLD15indem.csv)

**Comment by NofarGizra** [comment]
@niryariv 
The files do not match.
I understand that the Ethiopia IDs start from 201 (And not from 1 as in Kenya), but still - not all IDs match.
The Kenya IDs in the JSON file go up to 120, while in the CSV file they only go up to 109. This leaves a few divisions without an index, and thus without a color.

**Comment by NofarGizra** [comment]
![nocolor](https://cloud.githubusercontent.com/assets/3273122/3240600/8653b17a-f12d-11e3-8c62-6bb84bc04b7b.png)

**Comment by NofarGizra** [comment]
Here are the files I'm using:

CSVs for Kenya (Only 108 indexes in each):
https://github.com/Gizra/IBLI-map/blob/1/src/ibli-map/csv/KENYA_indexesLRLD.csv
https://github.com/Gizra/IBLI-map/blob/1/src/ibli-map/csv/KENYA_indexesSRSD.csv

JSON for Kenya+Ethiopia (Kenya indexes go up to 120):
https://raw.githubusercontent.com/Gizra/IBLI-map/1/src/ibli-map/json/kenya-ethiopia.json

**Comment by NofarGizra** [comment]
Also, please keep in mind that changes in **format** require development time to adjust to them, so try to avoid changes in names of things.
For example, in the new JSON file you provided (Kenya+Ethiopia) the word `DIV_ID` was changed to `IBLI_ID`, and the word `DIVISION` was changed to `DIVI_WOR`. These changes cause the whole map to stop working, and then we need to figure out what went wrong.
We now have figured out the changes and implemented them in the next version of the map (The one that includes Ethiopia), so we would be happy if you could please try to keep them as they are now in future versions of the JSON file.
Thank you!

**Comment by apurbashee** [comment]
@niryariv The division ids in new map (Kenya+Ethiopia) are different than previous map and hence they are different than the old .csv files. We will soon provide new Matlab and .csv files for Kenya. You already have the Ethiopian Matlab files via dropbox.

**Comment by niryariv** [comment]
okay, we'll hold on this until we get the new matlab/csv for Kenya.

**Comment by niryariv** [comment]
will be handled with the new map files
