### ISSUE TITLE
Make "IBLI" more prominent on HP

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#106]
Is it possible to make the "IBLI" more prominent on the home page and/or spell it out to make it bigger?

**Comment by niryariv** [comment]
@NofarGizra please change font size to 28px, color to #fff:

![screen shot 2014-06-09 at 2 08 30 pm](https://cloud.githubusercontent.com/assets/1771/3215843/6cae4c16-efc6-11e3-8db3-354ef43914eb.png)

**Comment by mldk-tech** [comment]
Done.

![logo](https://cloud.githubusercontent.com/assets/5812423/3255815/98e351aa-f20f-11e3-9cef-837852340c2d.png)
