### ISSUE TITLE
Publications page

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#108]
Google shared file created with some initial documents.  More to come.  @niryariv will we have the ability to add and delete?

**Comment by niryariv** [comment]
@bnedavies sure, you will be able to edit the page any time. I didn't get the share email from Google, could you post the link here? Thanks!

**Comment by bnedavies** [comment]
https://drive.google.com/folderview?id=0BwyWK0Vut1RBR2lNVURpdUV5Vms&usp=sharing

**Comment by niryariv** [comment]
@NofarGizra the page should contain links to the PDF/etc publications above
