### ISSUE TITLE
link footer icons to social sites

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#109]
https://twitter.com/IBLI_Kenya
https://twitter.com/IBLI_Ethiopia
https://www.youtube.com/channel/UCLcdSaDIcb6VHq3GflfQL0w
https://www.facebook.com/pages/Index-Based-Livestock-Insurance-Kenya-and-Ethiopia/1408317826105114

![screen shot 2014-06-09 at 11 45 14 am](https://cloud.githubusercontent.com/assets/1771/3214613/97ceae40-efb2-11e3-9a08-f6d6ecc9bc92.png)

**Comment by mldk-tech** [comment]
You can see the footer. we have a extra twitter icon for the second link.

![icon](https://cloud.githubusercontent.com/assets/5812423/3231136/2e8ac912-f0a9-11e3-8e4a-047090b3566e.png)

**Comment by niryariv** [comment]
please make sure to remove all the icons we don't have links for

**Comment by mldk-tech** [comment]
![icon](https://cloud.githubusercontent.com/assets/5812423/3231331/c57a8da2-f0aa-11e3-8f2d-d55a051b562e.png)
