### ISSUE TITLE
Toolchain step 1: convert the scripts to run automatically

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#11]
This is the first, and most critical task: Basically we'll need to be able to run the scripts automatically, so the script gets an input file and creates an output file which can then be input into the next script etc.

**Comment by alanorth** [comment]
This is the non-MATLAB part of the pipeline, right?  I need to talk to @apurbashee and get his MATLAB script + inputs to see if I can run programmatically it on Linux.

**Comment by niryariv** [comment]
@alanorth yep, that's Anton's part

**Comment by niryariv** [comment]
handled by @mbrv at https://github.com/Gizra/IBLI/tree/master/eMODIS_SHELL

**Comment by niryariv** [comment]
continued on #16 #19 #20 etc. closing
