### ISSUE TITLE
Events Calendar

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#110]
<iframe src="https://www.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=iblikenyaethiopia%40gmail.com&amp;color=%232952A3&amp;ctz=Africa%2FNairobi" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by niryariv** [comment]
use the following html:

``` html
<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;mode=AGENDA&amp;height=360&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;ctz=Africa%2FNairobi" style=" border-width:0 " width="360" height="360" frameborder="0" scrolling="no"></iframe>
```
