### ISSUE TITLE
Please change "Mifugo Maisha in Isiolo" picture to attached

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#112]
![img_20140119_093704 -revised](https://cloud.githubusercontent.com/assets/6724026/3226391/1cb3b952-f06c-11e3-9281-234e36bedd07.jpg)

**Comment by niryariv** [comment]
@bnedavies is there a better quality version of this pic? I'm concerned it won't look good on the homepage

**Comment by bnedavies** [comment]
no sadly, there isn't.  how about this one?
![20140219_111539](https://cloud.githubusercontent.com/assets/6724026/3270327/a2df0448-f2fe-11e3-8570-97e27c46c4e8.jpg)

**Comment by niryariv** [comment]
@NofarGizra please pick the one you think looks best
