### ISSUE TITLE
Picture titles on homepage

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#113]
Please revise as follows:

Index-Based Livestock Takaful in Wajir (same)
Index- Based Livestock Insurance in Marsabit (changed)
Index-Based Livestock Insurance in Borana (changed)
Index-Based Livestock Insurance in Isiolo (changed)

**Comment by niryariv** [comment]
1. Need to change "Index-Based Livestock Insurance Mifugo Maisha In Marsabit" to "Index-Based Livestock Insurance in Marsabit"
2. Make sure the word "in" is always lowercase in all 4 titles, instead of "In"

**Comment by bnedavies** [comment]
Remove "Mifugo Maisha"  - Should just read "Index-Based Livestock Insurance In Marsabit"
![title change](https://cloud.githubusercontent.com/assets/6724026/3480700/cba2f86e-0364-11e4-9fae-2be979ff0f1d.png)

**Comment by niryariv** [comment]
aren't we changing these to testimonials instead?

**Comment by bnedavies** [comment]
@niryariv see #154 - We are keeping pictures but will add a blurb underneath as their "testimonial" - on one or two, we could possibly have a video clip available when a user scrolls over the picture.  You were going to see if this was possible?

**Comment by niryariv** [comment]
@bnedavies do you have blurbs / videos?

**Comment by bnedavies** [comment]
@niryariv What is the best way to share these videos?  youtube links?

**Comment by niryariv** [comment]
Yes, that could work.

**Comment by bnedavies** [comment]
First video - IBLT in Wajir - https://www.youtube.com/watch?v=Cusa9tTuO2k&feature=youtu.be

IBLI in Marsabit - https://www.youtube.com/watch?v=1-w7iht20nw&feature=youtu.be

IBLI Borana - No video yet

IBLI in Isiolo - http://youtu.be/8v26L8rzguc

**Comment by bnedavies** [comment]
@niryariv here are the video links
