### ISSUE TITLE
This Welcome blurb should be on homepage next to video

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#117]
Welcome to IBLI

Since 2010, the International Livestock Research Institute (ILRI), and its partners, has been involved in designing, implementing, and assessing Index Based Livestock Insurance (IBLI) in Northern Kenya and Southern Ethiopia. IBLI’s objective is to improve pastoralists’ resilience to the considerable loss of livestock they incur during severe drought. 

This web platform aims to improve access to important information regarding IBLI such as the current condition of livestock in target areas as per the index that underlies IBLI, historical index readings, other relevant parameters of IBLI performance and general IBLI-related information. Automating these processes allows for near-real time information dissemination. Whether you are a pastoralist, an insurer, a government representative, or just an interested party, we welcome you and trust that herein you will find answers to most of the questions you have regarding the IBLI Program.

**Comment by niryariv** [comment]
text here:
![screen shot 2014-06-10 at 1 32 12 pm](https://cloud.githubusercontent.com/assets/1771/3228753/c068ac7e-f08a-11e3-8d7a-d9d908df701f.png)

**Comment by mldk-tech** [comment]
You can see that i add a text next to the youtube video.

![ibli homepage](https://cloud.githubusercontent.com/assets/5812423/3230598/8cf1e0ee-f0a4-11e3-87f8-f2a0e703a673.png)
