### ISSUE TITLE
Sign-up for IBLI updates page design

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#118]
Will we also have the ability to query information received?

https://docs.google.com/drawings/d/1-spER-CJyf23MAY_FTi4uRhxEIxENAMcUEMwjbd428U/edit?usp=sharing

**Comment by niryariv** [comment]
@bnedavies should we require users to fill all the fields?

**Comment by bnedavies** [comment]
No, I think only the email should be required.  What do you think?  I don't want it to be too bulky, but also need to balance that with people on our team who want lots of details...

**Comment by niryariv** [comment]
IMHO just email, but if we show all these fields it might discourage users from signing up altogether. i think we could solve in two ways:
1. reduce the number of fields to 4-5 with only email required
2. require only email and occasionally send surveys to email subscribers with all these details

what do you say?

**Comment by bnedavies** [comment]
Let's go with Option 2 but I would like email and phone number, in that case.  Sound ok?

**Comment by niryariv** [comment]
@NofarGizra is it possible to have MailChimp require phone as well as email on signup?

**Comment by NofarGizra** [comment]
@niryariv 
Yes.
