### ISSUE TITLE
Final Index Map - Page Design

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#119]
https://drive.google.com/folderview?id=0BwyWK0Vut1RBb3JmMUVpU29fcjQ&usp=sharing

**Comment by niryariv** [comment]
@bnedavies is this the same data as in homepage, divided for areas, or different data?

**Comment by bnedavies** [comment]
@niryariv It is the same data, but just in a different format, as shown in the page design - Is this possible?  It would be good to have the ability to generate PDF documents for this on a specific date.  E.g. for the March payout, we take the final reading on February 28, and we'd want to PDF this and then distribute to our partners.

**Comment by niryariv** [comment]
we'll need GIS files for each of the divisions - @apurbashee do you have those?

**Comment by bnedavies** [comment]
@niryariv  I changed the title to fit with our new headings.  On this tab, we just need to be able to generate and download PDFs of the _most recent_ final index reading (either Feb 28/29) or (Sept 30)
![final index map](https://cloud.githubusercontent.com/assets/6724026/3480456/04587822-0361-11e4-9998-ea70b41ead1e.png)

**Comment by niryariv** [comment]
@bnedavies since this will require more work (separate area maps + probably some PDF design) i suggest we move this task to v1.1 - what do you think?

**Comment by bnedavies** [comment]
@niryariv we can discuss but I think this needs to be in version 1.  I'm pretty sure everyone will say it's essential...

**Comment by niryariv** [comment]
OK. I understand there will be 5 maps - Wajir, Mandera, Garissa, Isiolo & Marsabit? @apurbashee can you produce shapefiles for these maps (including the IBLI ID for each division inside the map)?

**Comment by niryariv** [comment]
@bnedavies perhaps we can combine this and #120 into a "Past & Current Indexes" page, which will contain the maps in downloadable format. What do you think?

**Comment by bnedavies** [comment]
@niryariv yes, that's fine to combine them.  5 maps for version 1.  More in later versions.
