### ISSUE TITLE
Toolchain step 2: Check if the scripts can run on GDL

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#12]
Once #11 is done, the goal is to get everything running on Linux. If we can run everything on GDL that's ideal, otherwise we'll need to buy IDL for Linux.

(cc @bnedavies @alanorth - is there by chance a copy of IDL for Linux already in ILRI somewhere?)

**Comment by niryariv** [comment]
closing: will be using IDL for now

**Comment by iddodror** [comment]
Can I please be removed from these email alerts?

Thanks

Best wishes,

Iddo
_ _
Sent from mobile

On Apr 23, 2014, at 17:40, "Nir Yariv" <notifications@github.com<mailto:notifications@github.com>> wrote:

closing: will be using IDL for now

**Comment by niryariv** [comment]
I can't do it on my side, but you can easily do it by:
1. open https://github.com/Gizra/IBLI/issues
2. click "unwatch"

​3. select "Not watching"

**Comment by iddodror** [comment]
Well, I never signed up for this, and don't know my login...  Can the person who signed me up take me off the list?

Best wishes,

Iddo
_ _
Sent from mobile

On Apr 23, 2014, at 17:46, "Nir Yariv" <notifications@github.com<mailto:notifications@github.com>> wrote:

I can't do it on my side, but you can easily do it by:
1. open https://github.com/Gizra/IBLI/issues
2. click "unwatch"

​3. select "Not watching"

**Comment by alanorth** [comment]
Iddo you apparently have a GitHub account... so you'll have to try to log in and unwatch. :)

https://github.com/iddodror
