### ISSUE TITLE
add instructions on how to execute the IDL code on the server to the readme file

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#132]

**Comment by mbrv** [comment]
@niryariv 
How to run the shell ?
1. enter the server (41.204.190.27)
2. go to : "/opt/IBLI/dataProcessing/eMODIS_SHELL/"
3. type : idl -rt=emodisshell.sav -args "config_0905.txt">log.txt

the "config_0905.txt" is the config file and log.txt is the log file to which the output of the code will be written.
1. the code should run now.
