### ISSUE TITLE
Verify IDL results

### ISSUE THREAD

**Issue by mbrv** [Gizra/IBLI#135]
@niryariv 
We want to make sure that the code on the server gives identical results to what was previously achived.

@vrieling  - i'm going to use the latest division you sent me on the 23th of April. 

I'll start the run now and update once it's over.

**Comment by vrieling** [comment]
@mbrv There was an update of divisions sent later. Let me retrieve it and send it to you by e-mail.

**Comment by mbrv** [comment]
@vrieling  , thanks - can you please also sent the final CSV's you get ?

**Comment by vrieling** [comment]
@mbrv These are on my ftp (see the e-mail that I just sent you, and that was sent to all on 15 May).

**Comment by mbrv** [comment]
@niryariv 

There are small bugs in changing the Division file and subset ( for some reason it says we go out of the limits of the Images downloaded from USGS when i try to cut the relevant region from it).

will fix them and update you ASAP.

**Comment by mbrv** [comment]
@niryariv 

found the bug , i simply typed the bounding box incorrectly in the config file.

Nir , Please notice that to run the code with the new subset we have to overwrite the entire RAW Folder. Do you want me to keep a backup of the current data (do we have space for that?) or should i just delete it and run the process to subset the new data from USGS ?

**Comment by niryariv** [comment]
Just delete the old data if we need to rebuild it anyway

**Comment by mbrv** [comment]
upadte : the process is now running (corrected mistyped error in the config file)
it should take a while because it's redownloading the entrie data set from USGS with the new subset.

once it's done i'll compare the CSV output to the CSV output Anton Got and update.
(you can follow log file : log_19_06.txt )

**Comment by niryariv** [comment]
@mbrv no problem. is that working with the May 15th settings?

**Comment by mbrv** [comment]
yes - the once that are on the FTP Anton sent (i talked about that with Anton as well).

**Comment by mbrv** [comment]
@niryariv  @vrieling  Hi !
At last we have initial comparison results.

i ran the code using the "divisionID_K+E" division.

i'm not sure how to attach files here , so i'll send the new and original CSV via email.
@vierling you opinion will be greatly appriciated.

the two CSV files are not identical and it makes sence because they didn't run on exactly them same input ( the new run has 16 more periods in it than the original run).
but the changes seem to be not significant and the two tables are very correlated.
even more so after the cummulation.

i'm attaching plots of (blue - old run , red - new run ) :
1. zScore (Aggregated) for random period for each division :

![aggrandperiod](https://cloud.githubusercontent.com/assets/7194236/3386024/4c99b4e0-fc70-11e3-8913-60730f8bbe5a.png)
1. zScore (Aggregated) for random division for each period :

![aggranddiv](https://cloud.githubusercontent.com/assets/7194236/3386039/68173968-fc70-11e3-8ba0-27de97f6dfff.png)
1. zScore (Cummulated Aggregated) for random period for each division :

![cumaggrandperiod](https://cloud.githubusercontent.com/assets/7194236/3386047/6fdd5f74-fc70-11e3-8d75-21f538f69a3d.png)
1. zScore (Cummulated Aggregated) for random division for each period:

![cumaddranddivision](https://cloud.githubusercontent.com/assets/7194236/3386054/74a07f78-fc70-11e3-8ed7-4db71ed8a555.png)

@vrieling - are those results seem reasonable ? are the small changes due to extra 16 more periods make sense ?

Thanks ,
    Michael.

**Comment by vrieling** [comment]
@mbrv Looks overall reasonable. What do you mean with the 16 more periods? Are these also used to create new diagnostics? The other diagnostics file could be an explanation. Did you try the diagnostics-file that I had put on ftp? Perhaps another point is whether the same basis is used for z-scoring, but probably that is done. At least good to see that they match quite closely! Still Please note that tomorrow I am travelling. Can look at things in more detail next week with Nir perhaps...

**Comment by mbrv** [comment]
@vrieling 

Have a great Trip !

yes , the diagnostics file was recalculated using the extra samples.
i haven't tried the diagnostics file you put on the ftp.

i think that the important figure is 4 (cummulated aggregated zScore for a certain division) which is almost unmodified at all.

Again , Have a great Trip !

@niryariv  - you think that this comparison is enough to move on to the matlab part? 

Thanks,
    Michael.

**Comment by vrieling** [comment]
@mbrv Would be excellent to see if with my diagnostics file the result is 100% identical. Indeed, I agree for figure 4, but this is of course one division. Note that during updates it is better not to change the diagnostics file, otherwise results are not backward-compatible. Anyway, it seems that it works overall as expected.

**Comment by mbrv** [comment]
@vrieling . no problem , i'll set it to run this evening with your diagnostics file and see how it affects the final CSV files. thanks

**Comment by niryariv** [comment]
@mbrv done?

**Comment by niryariv** [comment]
done
