### ISSUE TITLE
Space Issues

### ISSUE THREAD

**Issue by mbrv** [Gizra/IBLI#136]
@niryariv  @alanorth 

Regarding the space issue : we ran out of space in "/var" - currently i don't see any way (correct me if i'm wrong) to save space. what we have in this folder is :
1. RAW Folder - a folder which contains the data from USGS - this folder will grow each 6-7 days in ~ 14 mega. 
2. PROCESSED - in this folder we have huge file which is basically a stacking of all the RAW data. this file will grow approximately in ~50 mega each 6-7 days.

so i think that ~3 Giga per year is the expected increment  - so if you could increase the volume only one time for ~ 30 Giga this should give us space for ~ 10 years (ofcourse not including other things that might be stored in "\var").

one possible other thing we can do is not to store the "RAW" folder and just download it on every run. but this means run-time will increase significantly ( we have to "download" ~7 Giga and growing from USGS on every run). 
and if you want to do that we'll have to find a solution to the disconnection problem (every once in a while the  connection to USGS times-out , i haven't investigated it too much but it will be significant to understand that if we choose not to have the USGS storage locally).

Nir , Alan , What do you think ?

**Comment by alanorth** [comment]
Thanks for the analysis @mbrv.  Two points from my side.  First, it seems we have some misused space (`PRCOESSED`):

``` console
# du -sh /var/www/data/*
584K    /var/www/data/CSV
4.0K    /var/www/data/CSV\
4.0K    /var/www/data/ppp
37G /var/www/data/PRCOESSED
50G /var/www/data/PROCESSED
9.3G    /var/www/data/RAW
```

Second, how often does the USGS data change?  Maybe we could delete only on the first run of the month or so?  Otherwise, I have no problems to add 10 - 20 GB the machine.

**Comment by mbrv** [comment]
Thank @alan !

you'r right!
I apologize but i  forgot and didn't notice that we still have the "PRCOESSED" folder which contains a disposable copy of the USGS storage.

i have deleted it and now it seems that the space issue is no longer an issue.

Thanks,
    Michael.
