### ISSUE TITLE
Where is IBLI Offered - Kenya

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#139]
@niryariv emailing you the map.  Is this a workable format for the webplatform.  If not, we'll need to ask @apurbashee for his help.

**Comment by niryariv** [comment]
So we'll use this image for both Kenya & Ethiopia - @bnedavies, do you want to write some text for the page?

![](https://raw.githubusercontent.com/Gizra/IBLI/master/dataProcessing/mapfiles/Ken+Eth/divisions.png)

**Comment by bnedavies** [comment]
Yes, you can use this map and we can combine the two pages into 1 page.  Will work on wording now and upload to google docs

**Comment by bnedavies** [comment]
https://docs.google.com/drawings/d/12lXDhw787zqXniSr7nVDhTo8PvhiSiQkcR5u0sS6Qhc/edit?usp=sharing

**Comment by niryariv** [comment]
@NofarGizra text in the link above^

**Comment by bnedavies** [comment]
@niryariv Move this map to "What is IBLI?" page?

**Comment by niryariv** [comment]
definitely. i suggest we create a github issue + google doc for that page, with the new format

**Comment by bnedavies** [comment]
ok, I will work on the new page and format this week.  Going to Ethiopia tomorrow, but should have some time at night.
