### ISSUE TITLE
Czndvi graphs

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#143]
@apurbashee @vrieling It was mentioned during Nir's presentation yesterday that we wanted to be able to generate the czndvi graphs on the webplatform.  Can you forward @niryariv what he needs to build this into the platform?

**Comment by vrieling** [comment]
Dear Bryn, Nir, Apurba,

Please find attached the most recent czndvi csv-file (this is the step before the temporal aggregation). The division-version is the one for Kenyan divisions and Ethiopian woredas. I also attach the kebele-version.

On another note, I understood that for Ethiopia we move now to 24 units (clustered kebeles). Potentially, we could add these directly to the Kenyan division, and not work with two separate aggregations anymore… However, the coming weeks I cannot work on it unfortunately.

Thanks again for the great interactions the past few days!

Anton
