### ISSUE TITLE
Update DNS record for ibli.ilri.org 

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#144]

**Comment by alanorth** [comment]
I assume we're getting ready for launch soon, yes?  I've just requested that the DNS be created to point to the correct server.  I'll keep you posted...

@niryariv In other news, do you think we'll be using HTTPS?  I think it's a good idea to use wherever possible, so I'll provision to open the ports for that...

**Comment by alanorth** [comment]
DNS done.  We'll handle HTTPS separately.

**Comment by niryariv** [comment]
@alanorth imho HTTPS not a huge deal in this project, since there's no user-specific content (ie no login) - outside of admin. assuming admin is being done at IBLI, it's your call based on security risks there.
