### ISSUE TITLE
Resize IBLI VM disk

### ISSUE THREAD

**Issue by alanorth** [Gizra/IBLI#148]
I talked with @niryariv yesterday and we agreed I'd add 30GB to the IBLI VM's disk image.  It'll take a few hours because I have to copy the current image somewhere with a newer `qemu-img` tool to do the resize.  I'll keep you posted.

**Comment by niryariv** [comment]
thanks @alanorth!

**Comment by alanorth** [comment]
Wow, this is actually more of a process than I imagined.  I'm just going to leave the machine as it is, and if space is still an issue when we want to launch, I can do it then.
