### ISSUE TITLE
Premium Table

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#149]
Please go over what is needed for webplatform to calculate premiums - past and current - with @niryariv

**Comment by bnedavies** [comment]
@apurbashee your help needed - what does Nir need to have webplatform automatically calculate premiums.  Please share with him

**Comment by bnedavies** [comment]
@niryariv changed name to fit with new design

After we have what we need from @apurbashee please design something in this format, but suggestions are welcome if you have a better way to lay it out!
![premium table](https://cloud.githubusercontent.com/assets/6724026/3480557/6463171c-0362-11e4-9403-75ebea3c10c0.png)

**Comment by niryariv** [comment]
from call w/ @apurbashee:
- use the 15 rate final premium: https://github.com/Gizra/IBLI/blob/master/dataProcessing/IBLIMatlab/OutRate/15rateFinal.csv
- premium rates update every season change (SRSD -> LRLD). we need to execute matlab every season change to process with the new data.
- past premiums: @apurbashee will create a csv with all the past premiums, we'll archive new premiums as they are calculated (update: [file is here](https://github.com/Gizra/IBLI/blob/master/dataProcessing/IBLI_unit_premium_rates.csv)]
