### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#15]
@niryariv We are working on preliminary design ideas for the webplatform.  One question though, can we use a different bootstrap theme for the admin function of the webplatform versus the view that the user will see? So, two themes?

**Comment by niryariv** [comment]
That could work, but it's pretty rarely needed - are you certain you'll need it? What's the reason for going with two themes?

**Comment by bnedavies** [comment]
Well, it was only because I liked themes like this for the user - http://wrapbootstrap.com/preview/WB05K85MJ

but I thought the information formatting in the admin templates might be useful?  -

http://wrapbootstrap.com/preview/WB0B30DGR
