### ISSUE TITLE
Launch Date

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#150]
Final date to launch whatever is ready, hiding some information as necessary.  Nir to propose after assessing staff needs.

**Comment by niryariv** [comment]
It looks like we'll target 1st week of September - but do keep in mind I'd need the materials from IBLI (especially #159)

**Comment by bnedavies** [comment]
@niryariv great.  Please just keep pushing us if we don't get you want you need from Apurba and Anton...

**Comment by woodardjoshua** [comment]
Bryn,

Apurba and I are working out these final details and will deliver in due
time. Thanks for your concern.

**Comment by bnedavies** [comment]
Great, thank you!

Bryn Davies  | Market and Capacity Development Manager| International Livestock Research Institute | ilri.orghttp://www.ilri.org/
P.O. Box 30709, Nairobi, Kenya  |  Tel: +254 20 422 3496  | Email:  b.davies@cgiar.orgmailto:b.davies@cgiar.org

IBLI ONLINE: http://livestockinsurance.wordpress.com/

ILRI ONLINE: Websitehttp://www.ilri.org/ | Newshttp://www.ilri.org/ilrinews | Repositoryhttp://mahider.ilri.org/ | Presentations http://www.slideshare.net/ILRI/presentations  | Ihttps://owa.cgiar.org/owa/redir.aspx?C=449f3cf5fc1b43e486d5def4409fcabc&URL=http%3a%2f%2fwww.flickr.com%2fphotos%2filri%2fsetsmageshttp://www.flickr.com/photos/ilri/sets| Filmshttp://ilri.blip.tv/posts| Facebookhttp://www.facebook.com/ILRIFanPage | Twitterhttp://www.twitter.com/ilri | Maps and locationshttp://www.ilri.org/contactus

ILRI is a member of the CGIAR Consortiumhttp://www.cgiar.org/  | better lives through livestock

The content of this email may be privileged or confidential. If you are not the intended recipient, please notify the sender immediately and do not copy, distribute or take action based on this email.

Please consider the environment before printing this email.
