### ISSUE TITLE
Streamline homepage

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#153]
1. Remove boxes immediately under map "sign-up for updates, publications, etc."
2. ~~Remove "Latest IBLI Updates" entirely - expand "welcome to IBLI and video" to fill space~~ Change tab order under Latest Updates

![screen shot 2014-07-03 at 3 28 20 pm](https://cloud.githubusercontent.com/assets/1771/3469391/0b260c54-02ae-11e4-90b1-deff5964d14b.png)

@alanorth any other streamlining/simplifying you can see?
@niryariv anything I forgot?

**Comment by alanorth** [comment]
I like the idea of streamlining -- less is more -- but we we have latest updates, we should probably put them there, eh?  I think that was going to be where the latest blog entries would be (do we still blog?).

**Comment by alanorth** [comment]
Also, if we're streamlining, we might want to sync with ILRI branded colors.  There's a guide somewhere, but we should be using proper reds and stuff.

**Comment by bnedavies** [comment]
@alanorth Is this what you meant? http://cgspace.cgiar.org/bitstream/handle/10568/21794/ILRI_logo_usage.pdf?sequence=2

We can put back the latest updates and have a blog feed on the homepage.  The Blog is active and being updated as we speak

**Comment by alanorth** [comment]
@bnedavies Yeah, at least we could use #662222 for ILRI red, then some other.  Not sure what color we'd use for the second, lighter red tone though.  @niryariv maybe we could steal some colors from the ilri.org website?

For the blogs, I dunno.  Will we link to it somewhere else on the website?
