### ISSUE TITLE
IBLI On the Ground - Homepage

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#154]
Show short text under each photo.  No additional links/redirects

@niryariv to check if we possible to scroll over photo and see link to a video

**Comment by niryariv** [comment]
@bnedavies do you have content for this, or shall we push it to v1.1?

**Comment by bnedavies** [comment]
@niryariv where did the pictures go for IBLI - Isiolo, IBLI - Borana, etc. etc below the youtube video on the home page?

**Comment by niryariv** [comment]
what should the images do - should we open a "IBLI in .." page for each, or play a video?

**Comment by bnedavies** [comment]
A few were going to play a video...the ones that don't have videos, we can link to a page?  I believe I already sent all these links previously, but let me know if I need to repost

**Comment by niryariv** [comment]
@bnedavies can u please resend me the content the images should link to? Can't find it here..

**Comment by bnedavies** [comment]
see #113

**Comment by niryariv** [comment]
thanks! opened #241 - closing this
