### ISSUE TITLE
Homepage - Top Menu

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#155]
Top Heading should read as follows:

IBLI -- What is IBLI? -- Get IBLI -- Information -- About Us
1. "What is IBLI?"  Should link to 1 page (use page already created for now, but will add more text: http://dev-ibli.gotpantheon.com/content/what-ibli )
2. "Get IBLI" links to 1 page (need to create: #168)
3. Under "Information":
   - [Blog](http://livestockinsurance.wordpress.com/)
   - ~~Final Index Map (@bnedavies do we need this or just use the homepage?)~~
   - Past Index Maps (see #199)
   - Premiums Table (see #149)
4. Under "About Us":
   - ~~Team (need to create: #171)~~ (moved to 1.1)
   - Partners (need to create: #170)
   - [Gallery (Flickr)](https://www.flickr.com/photos/125283442@N04/)
   - [Contact Us](http://dev-ibli.gotpantheon.com/contact-us)

**Comment by niryariv** [comment]
reopening..

**Comment by bitamar** [comment]
Fixed on dev
