### ISSUE TITLE
Homepage Map - LEGEND

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#157]
![legend](https://cloud.githubusercontent.com/assets/6724026/3469639/aa54bbf6-02b1-11e4-8a68-bf851a533331.png)
1. Remove %s from Legend
2. Add wording next to colors as follows:

Green = Good Conditions
Yellow = Average Forage
Orange = Declining Forage
Red = Forage Scarcity
Black = Severe Drought (Payout)
1. Add title to Legend - Forage Scarcity Map
2. When scroll over an area of the map, by legend you will see "division name = Text under 2" instead of %

**Comment by bnedavies** [comment]
We could also put this below the legend.  @niryariv what do you think?

![legend ethiopia](https://cloud.githubusercontent.com/assets/6724026/3479774/a211ec9c-0357-11e4-8ca3-5ac91053a9e2.png)

**Comment by niryariv** [comment]
could definitely put it, but I would suggest trying to make it even more simple to understand - for example, does the number range really make a difference to the user?

**Comment by bnedavies** [comment]
The number range does matter for payout...It might have to be a compromise to use the legend with text, but include this as well for the insurers/academics using the website.

**Comment by bnedavies** [comment]
@niryariv I still think we put the whole thing with text as well but perhaps on the right-hand side bottom?  It's important for payout and any insurers/academics using the site...

**Comment by niryariv** [comment]
no problem. could you provide this as an image file (PNG etc)?

**Comment by bnedavies** [comment]
@apurbashee can you provide this in the format Nir needs?

**Comment by niryariv** [comment]
@apurbashee any updates?

**Comment by apurbashee** [comment]
Bryn and Nir,
I think you are looking for image (e.g. PNG) file for the above legend not
for the color maps. In GIS when I do the color map there is option of
saving the map as PNG format. BUT the legend was done in power point, I am
not sure how to get a PNG form from there.
Apurba

**Comment by bnedavies** [comment]
@apurbashee Can you email the powerpoint version?

**Comment by bnedavies** [comment]
@apurbashee we need this legend in another format - can you please create?

**Comment by apurbashee** [comment]
I am attaching a powerpoint (this is index announcement March 2014).. see
if you can use the legend from there.
Apurba

**Comment by niryariv** [comment]
@apurbashee didn't get an attachment - it's ok, we'll have a designer fix this.

**Comment by niryariv** [comment]
closing for #206
