### ISSUE TITLE
Install IDL on the Data Processing Linux server

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#16]
(cc @alanorth)

In order to run Anton's toolchain, we'll need IDL, which can be purchased [here](http://www.exelisvis.com/ProductsServices/IDL.aspx) - but it's probably a good idea to see if ILRI already has a license, since there's a fair chance it's already being used there.

**Comment by alanorth** [comment]
Ok, @niryariv.  I'm checking if ILRI has a license already.

**Comment by alanorth** [comment]
Ok, I talked to some people in RMG (Research Methods Group at ILRI) and they have a license, but it's node-locked and runs on Windows.  We'll definitely have to get our own license.  RMG says they can help procure that, as they get some special rate for the CGIAR.

@bnedavies you can talk to Agnes Odanga (the RMG secretary) about arranging this.  She's away until March 17th apparently... but yeah, she should be the one to talk to.

**Comment by niryariv** [comment]
@bnedavies - any updates from Agnes on the IDL license?

**Comment by bnedavies** [comment]
From Fred - I believe we are to install IDL on one seat. Right? Kindly provide host info (hostname, mac address) so we can process a request for the  license.

Bryn,
Our cost for a single license is $1136

Alan asked about compatibility with Linux server...waiting on response from Fred (from RMG at ILRI)

**Comment by niryariv** [comment]
@bnedavies @alanorth - status? We're close to having a fully automated IDL chain, will be able to test run it on ILRI server soon

**Comment by bnedavies** [comment]
@alanorth Anything you need me to do for the IDL license?

**Comment by alanorth** [comment]
@bnedavies Nope!  I actually haven't had time to look at it yet, but Fred (the contact in RMG who does the licensing) was on leave until April 24th anyways, so I'll ask him tomorrow.

**Comment by bnedavies** [comment]
@alanorth great, thank you :)  Let me know if you need me to track him down, since he sits in Mara

**Comment by alanorth** [comment]
Ok, I've gotten the license for IDL.  I will acquire the software and try to install it in the Linux server, and keep you posted...

**Comment by alanorth** [comment]
@niryariv and @mbrv have access to the server, and the next step is IDL... I completely blanked yesterday when talking to @mbrv about IDL, forgetting that we already had the license and software for it!

``` console
$ ls ~/Downloads/idl_linux/
envi51idl83r4.tar.gz  idl83envi51linux.x86_64.tar.gz  InstalltionInstructions.txt
```

**Comment by niryariv** [comment]
great, thanks! assigning the issue to you (if you prefer @mbrv or myself install, just let me know - I suppose that would require root?)

**Comment by alanorth** [comment]
Ok. got IDL installed today, but having problems starting the license server (damn proprietary software!!).

``` console
$ sudo /etc/init.d/sys5_idl_lmgrd start
/opt/exelis/idl83/bin/lmgrd: 459: exec: /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd: not found
```

But this file _does exist_:

``` console
$ ls -l /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd
-rwxr-xr-x 1 root root 1429728 Nov 15 15:51 /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd*
```

And it's executable... which made me think maybe it was a 32-bit issue, but the file is 64-bit:

``` console
$ file /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd
/opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, stripped
$ /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd
-bash: /opt/exelis/idl83/bin/bin.linux.x86_64/lmgrd: No such file or directory
```

Very bizarre... did you install IDL in Linux, @mbrv?

**Comment by alanorth** [comment]
Ooh, apparently my headless Ubuntu 12.04 LTS server install was super minimal; I needed `lsb-core`.  Now `idl` is working!

**Comment by alanorth** [comment]
@mbrv can now log in and test... I have copied the IBLI repo to `/opt/IBLI`, but I'm not sure where we will want it in the end.  I assume the IDL scripts are `dataProcessing/eMODIS_IDL_scripts/`??

**Comment by niryariv** [comment]
![](http://media2.giphy.com/media/gCMyCPHTUuPSM/200_s.gif)

closing - @mbrv over to you at #36
