### ISSUE TITLE
Rate Calculator

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#160]
Each area has its own premium rate. 

The user enters the data into a form with 4 fields: # of Camels, Cows, Goats & Sheep.

@bnedavies please fill in the rest..

**Comment by bnedavies** [comment]
@apurbashee please share what Nir needs to have the webplatform calculate the premiums each season automatically.  

Formula for rate calculation is as follows:

1 cow = 1 TLU = 25,000
1 camel = 1.4 TLU = 35,000
1 sheep or goat = 0.1 TLU - 2,500

(#cows \* 25,000 + #camels \* 35,000 + #sheep/goats*2500) \* Premium rate for division

**Comment by niryariv** [comment]
@nader77 some notes:
- the calculator will open on the map popups. each popup will have a link "Calculate your rate", clicking it shows the calculator UI (in hide/show element)
- the UI has 3 input boxes for integers (assume 2 digits) - cows / camels / sheep & goats - and a "calculate" button.
- Each input box has an icon next to it: 
  [Camel](http://thenounproject.com/term/camel/36061/)
  [Cow](http://thenounproject.com/term/cow/5167/)
  [Sheep](http://thenounproject.com/term/sheep/8389/)

**Comment by bnedavies** [comment]
A few issues - 
1. I'm not getting the pop-up when I scroll over like it was doing before - I have to click to get the information?
2. The premium calculator does not seem to be calculating correctly?  What equation are you using?
3. Instead of "Your calculated rate is" please change to "The approximate cost to insure these animals is"

**Comment by nedSaf** [comment]
1. Yes now it shows on click.
2. formula:

``` js
calculatedSum = (cows * 25000 + camels * 35000 + sheep_goats * 2500) * (scope.premiumRate / 100);
```

Is it wrong ?

**Comment by niryariv** [comment]
1. We made it open by click instead of hover - it was harder to use in the hover mode. we can change back if you prefer
2. Can we change to "**Approximate cost:**" (ie assuming the user understands it's for the inputted values, and in the context of the insurance)?

**Comment by bnedavies** [comment]
1. Ok, is there anyway for the name of the division to come up at the very least when hovering?
2. How about "approximate cost to insure"?
3. @nader77 it's a bit more complicated than that.
4. APA in Isiolo & Marsabit uses values of camel = 28,000, cow = 20,000, sheep/goat = 2,000
5. TIA in Isiolo, Wajir, Garissa, Mandera uses values of camel = 35,000, cow=25,000, sheep/goat = 2,500
6. OIC in Ethiopia uses values of camel = 10,000etb, cow=6000 etb, goat/sheep = 8000 etb

e.g. when I click on "Eldas @ 7.55% and list one cow it shows "Your calculated rate is: 1,997.50 " - but this should equal 1887.50.

**Comment by nedSaf** [comment]
1. I added a hover with the name of the province, when clicking on the province the rest of the data will appear with a fixed popup, Until its closed, the other hover popups will not appear (To prevent overlaying of popups.)
2. The text is changed.

3.+4.+5.+6. Should i add another field to the provinces which has more than one insurer ? (A select-list to select the correct insurer.)

Just to make sure i understand, The calculator does the calculation according the insurer controlling the District ?

**Comment by niryariv** [comment]
@bnedavies we're doing the per-insurer calculations, are there any insurers other than those listed in sections 4-6?

**Comment by bnedavies** [comment]
@niryariv no, those are the only ones for this version.

**Comment by bnedavies** [comment]
seems like something is still wrong with the calculator?

**Comment by niryariv** [comment]
@bnedavies we'll push a new version later today

**Comment by bnedavies** [comment]
@niryariv great! :)

**Comment by nedSaf** [comment]
[Pushed](http://dev-ibli.gotpantheon.com/)

**Comment by niryariv** [comment]
@bnedavies Eldas showing correct rate now :)

![screen shot 2014-09-29 at 5 06 33 pm](https://cloud.githubusercontent.com/assets/1771/4442715/da6fb050-47e1-11e4-8c81-8191c723e90d.png)

**Comment by bnedavies** [comment]
Yep, looks like the calculations are working!  Please just make sure the pop-ups aren't cut off when someone selects Ethiopia
