### ISSUE TITLE
Map popups

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#161]
when hovering or clicking on an area in the map, we'll show a popup with text in the following format:

**AREA NAME**
Premium Rate: **5.1%**
Next Sales Window: **Aug/Sept or Jan/Feb** (whichever is later)
Next Potential Payout: **October or March**
Insurer: [**Takaful or APA**]() (links to insurer website)

[Calculate your rate](https://github.com/Gizra/IBLI/issues/160)

**Comment by bnedavies** [comment]
A few comments:

Next potential payout can be either March or October - needs to read off Sales window.  If sales window reads jan/feb - payout should read October.  If sales window reads aug/sept - payout should read march.

Insurer - APA is in Isiolo and Marsabit; Takaful is in Wajir, Isiolo, Mandera, and Garissa

For Isiolo - two options will need to be listed

Takaful website http://www.takafulafrica.com/
Contact: Habib Shatry, 0712 764 888

APA Website http://www.apainsurance.org/
Contact: Erastus Nege, 0720 671 213

**Comment by niryariv** [comment]
@bnedavies how do we determine the sales window? just the nearest window to the current date, or is there any other information we should consider?

**Comment by bnedavies** [comment]
@niryariv  - The nearest window, but in the future -  sales windows are January 1 to February 28/29 and August 1 to September 30th

**Comment by niryariv** [comment]
sure

**Comment by bitamar** [comment]
**Moyale** doesn't have an insurer defined above.

**Comment by niryariv** [comment]
@bitamar no insurer for Moyale yet, just display "TBD" instead of insurer name

**Comment by bitamar** [comment]
@nader77 - The map borders need to be large enough to include the popups, also when zoomed in

**Comment by nedSaf** [comment]
Fixed on PR [#8](https://github.com/Gizra/IBLI-map/pull/8)
