### ISSUE TITLE
create Get IBLI page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#168]
@bnedavies do you have content for this page?

**Comment by bnedavies** [comment]
@niryariv use these details for Get IBLI Page for now.   

![get ibli contact info](https://cloud.githubusercontent.com/assets/6724026/3749201/3eded0e4-17e9-11e4-8b39-d31207e1745a.png)

**Comment by niryariv** [comment]
@bnedavies could you send the APA logo? I think we only have Takaful

**Comment by bnedavies** [comment]
Just emailed you this

**Comment by niryariv** [comment]
![screen shot 2014-08-04 at 12 31 23 pm](https://cloud.githubusercontent.com/assets/1771/3795339/36b4e4f6-1bba-11e4-93fb-b8fd03ec238a.png)
