### ISSUE TITLE
create Partners page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#170]
@bnedavies do we have content for this?

**Comment by bnedavies** [comment]
@niryariv please just insert our logo + partners logo that were originally on homepage.  A few to be added.  What is the best way to send these to you?  Or can you grab from their websites?

THESE YOU HAVE ALREADY:
ILRI
Takaful
AusAID
DfiD
EU
MercyCorps

TO BE ADDED:
APA
World Vision
Kenya Markets Trust

**Comment by niryariv** [comment]
@nader77 note this is linked from the top menu (under About Us > Partners). Create as a place holder for now with the logos we have the current site in the "Partners" tab under "Latest IBLI updates":

![screen shot 2014-09-03 at 10 03 56 am](https://cloud.githubusercontent.com/assets/1771/4130499/8c4b5cca-3338-11e4-90a6-dee97c585f77.png)

**Comment by niryariv** [comment]
- [x] add ILRI logo

![](http://ilri-comms.wikispaces.com/file/view/ILRI%20logo.png/356665200/ILRI%20logo.png)

**Comment by nedSaf** [comment]
@niryariv Done on PR #205

**Comment by niryariv** [comment]
done
