### ISSUE TITLE
implement historical index maps

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#187]
- [x] move the zoom control to the bottom right corner of the map
- [x] add a select box in the top right corners of previous seasons, using data from the [CSV](https://github.com/Gizra/IBLI/blob/master/dataProcessing/zCumNDVI_Percentile.csv)

![screen shot 2014-08-31 at 5 04 19 pm](https://cloud.githubusercontent.com/assets/1771/4102096/4f0c9f3a-3118-11e4-99ac-56fbcf4ca1fd.png)

**Comment by bitamar** [comment]
https://github.com/Gizra/IBLI/pull/188
https://github.com/Gizra/IBLI-map/pull/6
Merged

**Comment by niryariv** [comment]
- [ ] fix to work on FF (and IE etc)
- [x] order select box options from most recent season downwards
- [x] replace "2014S" with "2014, Short season" etc
- [x] remove current index legend (we'll replace with [new legend](https://github.com/Gizra/IBLI/issues/157#issuecomment-48021313) later on):

![screen shot 2014-09-02 at 8 39 57 am](https://cloud.githubusercontent.com/assets/1771/4114239/ecb7c236-3263-11e4-9ad6-555760a99165.png)

**Comment by bitamar** [comment]
@nader77 - Notice the select does work on ff when using the keyboard. The problem seems to be that after clicking the select, the focus is hijacked by the map.

**Comment by bitamar** [comment]
@nader77 - Please continue this on https://github.com/Gizra/IBLI-map/pull/7

**Comment by bnedavies** [comment]
@niryariv when will legend be added?  Please let me know if you are waiting on something from us?

**Comment by niryariv** [comment]
@bnedavies we have [this](https://github.com/Gizra/IBLI/issues/157#issuecomment-48021313) which we can't really use as-is, we'll either reimplement in HTML or redesign the image.

**Comment by niryariv** [comment]
done
