### ISSUE TITLE
modify IDL code to be cron-aware

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#19]
basically this means that when the script is called it checks what's latest processed NDVI data, then checks for new data on USGS - if the data in USGS was already processed, the script just quits (maybe outputs a message like "no new data - latest processed was [date]"

**Comment by mbrv** [comment]
The process is now cron-aware : it asks for no input from the user ( the config file used to be chosen by a user prompt which is not replaced with an input argument) and thus can be ran automatically without human intervention.

a small issue that i saw is that when running a code through IDL VM - it always pops up an intro message which requires a human to click on a "click here to continue" button : i'm trying to see if it is possible to disable this intro message.

**Comment by niryariv** [comment]
1. does the code also check if there's new data (ie if it was run the previous day, and no new USGS data was released, it should quit rather then re-process already processed data)?

~~1. is it possible to run without the IDL VM? eg, just running `idl emodisshell.sav -args "config.txt"`~~ moved to #20
