### ISSUE TITLE
add premium rates to the unit popup

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#196]
take the values from here (always the 15rate column): https://github.com/Gizra/IBLI/blob/master/dataProcessing/IBLI_unit_premium_rates.csv

**Comment by niryariv** [comment]
show this under the area name, eg:

**AREA NAME**
Premium Rate: **5.1%**

(to calculate the rate, multiply the value under rate15 *100. note that not all history maps will have rates, since the insurance only exists for a couple of years)

**Comment by nedSaf** [comment]
@niryariv I have more than 1 column of `15rate`, Should i take all of them and calculate the average or what ?

**Comment by niryariv** [comment]
Match each one to the correct year/season

**Comment by niryariv** [comment]
fixed
