### ISSUE TITLE
changes to premiums table UI

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#197]
- [x] cancel the animation
- [x] allow opening more than one year at a time: when a user opens a new year, don't close the one that's already open. allow the user to close an open year by clicking on the title

**Comment by niryariv** [comment]
also:
- [x] show IBLI unit and DIV_WOR data
- [x] change all values to % ( x 100, round to 2 decimal points: 0.046893 -> %4.69 )

**Comment by niryariv** [comment]
remove DIVI_WOR column, rename IBLI_UNIT to UNIT

**Comment by niryariv** [comment]
cancelled, see below
~~from @bnedavies: Please only show 15rate. All others can be removed. Please change "15rate" to "Premium Rate"~~

~~In this case we can probably just have all years open, no need for the show/hide system.~~

**Comment by bnedavies** [comment]
@niryariv We've changed our minds - Apologies!!  Please keep all rates but we need to change the names of the headings.

Premium rate @ 10% trigger/ CURRENT PREMIUM rate @ 15% trigger/premium rate @ 20% trigger, etc etc.

**Comment by apurbashee** [comment]
Sorry about this. Although at present only 15 % trigger  contracts are
operational, we would like to provide flexibility on the web. Thanks Bryn
for correcting.
Apurba

**Comment by niryariv** [comment]
OK, but this text won't fit the column :) Perhaps we could just give the 15% column a different background color to make it stand out?

@apurbashee, while we're on this - what's the meaning of the trigger? Does it relate to the index, eg 20th percentile?

**Comment by apurbashee** [comment]
Yes. 15% trigger means when the index falls below 15 percentile the
contract would payout..

**Comment by nedSaf** [comment]
@niryariv So what should i do here ?

**Comment by niryariv** [comment]
- [x] return to the previous format (showing all rates) 
- [x] give the 15 rate a light yellow bg
- [x] change "%x rate" to "%x trigger"
