### ISSUE TITLE
get MATLAB / Excel / VB code in the repo

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#2]

**Comment by niryariv** [comment]
@bnedavies assigning to you - basically we just need the Matlab code now, since the Ethiopia Excel/VB will be replaced with Matlab.

This is required so Alan can start with #5

**Comment by bnedavies** [comment]
Apurba should probably be in charge of this since he will be the one putting the Ethiopia contract into Matlab?

**Comment by bnedavies** [comment]
Just spoke to @apurbashee - he says the Ethiopia contract will be in matlab by the 1st week of March.  @alanorth Can we test the Kenyan code in Octave if it is ready earlier?

**Comment by niryariv** [comment]
I suggest we test the code that currently runs on Windows - we can verify the inputs/outputs match on Win/Linux (with Matlab on Linux for now, to minimize the # of variables)

**Comment by alanorth** [comment]
@bnedavies I don't have high hopes for running it in Octave.  I have just installed Matlab on Linux today, so the next step here is to run it then figure out how to do it "the Linux way" (with no pointing and clicking).

Also, this is a good experience in figuring out how "compartmentalized" @apurbashee's code is (which input files do we need, etc to get it running on my computer).

**Comment by bnedavies** [comment]
@alanorth ok, good to know.  @apurbashee is sending the requirements for #4 & #7 today so you and Nir can start work and test on Linux

**Comment by woodardjoshua** [comment]
Fyi, this functionality has been converted into matlab.

**Comment by niryariv** [comment]
Great, thanks
