### ISSUE TITLE
set config file in IDL command line

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#20]

**Comment by mbrv** [comment]
this was set. 
to run the compiled code with an input config file from the command line you simply write : 

idl -vm=emodisshell.sav -args "config.txt"

where "config.txt" can be any path to a valid configuration file.

**Comment by niryariv** [comment]
@mbrv is it possible to run without the IDL VM? 

eg, just running `idl emodisshell.sav -args "config.txt"` - with IDL itself installed on Linux, not the VM.
