### ISSUE TITLE
show only latest data on homepage

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#202]
1. notice the percentiles file now uses IBLI_UNIT_ID column name instead of ADMIN_ID
2. also, the file now shows the latest season info
- [x] in HP, show only the latest season info (ie, whatever is the last column - currently 2014L)
- [x] move the top right select box to the map at the Past Index Maps page (#199)

**Comment by bnedavies** [comment]
@niryariv for the map with pop-up boxes on homepage:
1. It needs to show IBLI Unit boundaries - it's showing 2 North Horrs at moment.
2. For Pop-up boxes, please add items as follows:

NORTH HORR
Current Premium Rate: 8.15%
Next Sales Window:
Aug/Sept 2014 (NEED YEAR BUT WILL THIS AUTO UPDATE FROM SEASON TO SEASON?)
Next Potential Payout:
March 2015 (NEED YEAR BUT WILL THIS AUTO UPDATE FROM SEASON TO SEASON?)
Insurer:
APA

**Comment by bnedavies** [comment]
@niryariv can we also make the map on the home page bigger?

**Comment by niryariv** [comment]
@nader77:
- [x] verify the unit name is read from the IBLI_UNIT column, not the DIVI_WOR one (that's the reason we have 2 North Horrs
- [x] add year to the sales window/potential payout dates

@bnedavies yep, this will update automatically from season to season)

**Comment by nedSaf** [comment]
I added the year and the unit name is from "IBLI_UNIT",
one question, The year to the window/potential payout dates should be the year of the period that is selected from the list  (In past index map, of course) ?

Screenshot of the popup now:
![selection_022](https://cloud.githubusercontent.com/assets/7369740/4200931/b2401f40-3817-11e4-8981-c5c264ca1f61.png)

**Comment by niryariv** [comment]
good point. in the past index maps, dont show the payout / sales window / insurer information.

**Comment by nedSaf** [comment]
Like this ?
The latest season:
![selection_024](https://cloud.githubusercontent.com/assets/7369740/4201128/8bcf6020-381a-11e4-98fc-0cc572b9d335.png)

Past season:
![selection_025](https://cloud.githubusercontent.com/assets/7369740/4201135/a4fd8dd8-381a-11e4-98eb-85c5389974a4.png)

**Comment by niryariv** [comment]
yes

**Comment by bnedavies** [comment]
@niryariv @nader77 there is an error.  "next potential payout" should read "March 2015.

Also, can we revise/add a few things?
1. Instead of "Next Potential Payout" change to "Next Potential Payout for NEW purchasers" = March 2015
2.  Add line after "Next Potential Payout for current policyholders" = October 2014

**Comment by niryariv** [comment]
@nader77 - please verify the next date is always in the future :)

@bnedavies - the new text format seems a bit long to fit in the popup, and since it's the same text for all areas, perhaps we should move out of the popups, eg to a text box on the top right corner of the map?

**Comment by niryariv** [comment]
- [ ] verify the next date is always in the future
- [ ] on the top right corner, add a box (same bg color / opacity as the legend box) with the text:

**Next Potential Payout for NEW purchasers** Month Year
**Next Potential Payout for current policyholders** Month Year

**Next Sales Window** Month Year

@bnedavies I understand the new purchasers' payout is always at the payout window after the next one?

**Comment by bnedavies** [comment]
Yep.  If you buy now (Aug/Sept 14), your first potential payout is March 15.  2nd potential payout is October 15.  If you buy in Jan/Feb 15, your first potential payout is October 15, then March 16.
