### ISSUE TITLE
add legend to the map

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#206]
[PSD here](https://drive.google.com/file/d/0B7Lzf69iarhdUFJZckdzQ0F4ZkU/edit?usp=sharing). Please add on HP and historical maps. The legend should display in the bottom right corner, like so:

![map](https://cloud.githubusercontent.com/assets/1771/4199016/b145ca2a-3800-11e4-8723-efb5e159ea5e.jpg)

**Comment by bnedavies** [comment]
@apurbashee should we add some simpler wording - black = payout, green = good conditions, no payout?

**Comment by bnedavies** [comment]
Please change wording on legend - 

Payout = worst forage conditions in 100 seasons
Good Conditions, No Payout = best forage conditions in 100 seasons

![legend](https://cloud.githubusercontent.com/assets/6724026/4353649/fc8a9760-4235-11e4-8dea-f05efc06a5e5.png)

**Comment by niryariv** [comment]
@bnedavies do you mean replace the existing text with "Payout" and "Good conditions, no payout" - or show both the old & new text?

**Comment by bnedavies** [comment]
@niryariv replace existing text with "good conditions, no payout" and "bad conditions, PAYOUT"

**Comment by niryariv** [comment]
@nader77 see above ^ - can you do it or should we ask Keren to do that in the PSD?

**Comment by nedSaf** [comment]
I think i can do it on my on, I will update you.

**Comment by Moo64c** [comment]
![legend](https://cloud.githubusercontent.com/assets/2690042/4488982/733d960a-4a15-11e4-9931-eebe3bc3b03b.png)
@nader77 they meant this?

**Comment by Moo64c** [comment]
Fixed 
![legend](https://cloud.githubusercontent.com/assets/2690042/4488997/e2244910-4a15-11e4-8236-528679edc0f6.png)

**Comment by Moo64c** [comment]
@nader77 Nir asked for some changes.
![legend](https://cloud.githubusercontent.com/assets/2690042/4489050/b1ffa2c4-4a16-11e4-8a56-74fd8bfc9747.png)

**Comment by Moo64c** [comment]
Cropped
![legend](https://cloud.githubusercontent.com/assets/2690042/4489086/f6130582-4a16-11e4-916b-1a63b60761dd.png)

**Comment by bnedavies** [comment]
Spelling error - should be "increasing seasonal forage conditions" not "conditional"

Also, is this box auto-updating?
![info box - homepage](https://cloud.githubusercontent.com/assets/6724026/4559572/664dad40-4eed-11e4-8d2f-533424e06f0f.png)

**Comment by niryariv** [comment]
Box is auto updating. Moving the spelling fix to #259. Should we also capitalize "increasing"?

**Comment by bnedavies** [comment]
Yes - thanks!

**Comment by niryariv** [comment]
ok, closing for #259
