### ISSUE TITLE
add readme.txt to eMODIS_SHELL

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#21]
explaining how to run the code from shell, what's needed, which data is stored where etc

**Comment by mbrv** [comment]
Added

**Comment by niryariv** [comment]
thanks! could you add some info on:
1. meaning of each parameter in the config.txt file 
2. what each file does, and the order they run

**Comment by niryariv** [comment]
also, is the tabbing in https://github.com/Gizra/IBLI/blob/master/eMODIS_SHELL/config.txt#L7 required?
