### ISSUE TITLE
text for the "Contact Us" page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#211]
@bnedavies could you give us some text for this paragraph?

![screen shot 2014-09-10 at 11 09 41 am](https://cloud.githubusercontent.com/assets/1771/4214416/f46dbcaa-38c2-11e4-83cf-050d08535f32.png)

**Comment by bnedavies** [comment]
IBLI Project Manager
International Livestock Research Institute (ILRI)
P.O. Box 30709 – 00100, Nairobi – Kenya
Tel: +254-20-422 3000 (SwitchBoard) / 3043 (Direct)
Fax: +254-20-422 3001

MAP: https://www.google.com/maps/@-1.27137,36.725557,1605m/data=!3m1!1e3?hl=en

**Comment by bnedavies** [comment]
For blurb - 

If you have additional questions and/or comments about Index-Based Livestock Insurance, please complete form below and we will respond as soon as possible.

**Comment by nedSaf** [comment]
@niryariv @bnedavies We already have the address on the right side of the page, Please Provide another text to be above the form:
![selection_033](https://cloud.githubusercontent.com/assets/7369740/4231593/c9ba9ca0-3992-11e4-9639-d5c2483a669b.png)

Thanks.

**Comment by niryariv** [comment]
@nader77 the text Bryn sent is for above the form:

```
If you have additional questions and/or comments about Index-Based Livestock Insurance, please complete form below and we will respond as soon as possible.
```

**Comment by nedSaf** [comment]
Ok sorry.

**Comment by niryariv** [comment]
no worries :)

**Comment by niryariv** [comment]
done
