### ISSUE TITLE
Imges attributions

### ISSUE THREAD

**Issue by nedSaf** [Gizra/IBLI#223]
Cow: Cow by Alessandro Suraci from The Noun Project
Camel: Camel by Yair Cohen from The Noun Project
Goat: Goat by Anand Prahlad from The Noun Project

**Comment by niryariv** [comment]
we'll add this later in a credits page, for now put this on hold

**Comment by bnedavies** [comment]
@nader77 I like these but Kenyan sheep/goats are much skinnier...can you find something closer to this?  Maybe do a goat and a sheep together ?
![animals](https://cloud.githubusercontent.com/assets/6724026/4352863/89f06b30-422b-11e4-8cf9-5f346ec1432e.png)

**Comment by niryariv** [comment]
@bnedavies we took the icons from this site - is there anything there you'd prefer? http://thenounproject.com/search/?q=goat

**Comment by bnedavies** [comment]
this one looks close to the goats we have here - http://thenounproject.com/term/goat/18892/

**Comment by niryariv** [comment]
@Moo64c please replace sheep with above goat ^

**Comment by niryariv** [comment]
done
