### ISSUE TITLE
fix contact button in the "about us" page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#224]
leads to http://dev-ibli.gotpantheon.com/content/contact.html (which is 404) instead of http://dev-ibli.gotpantheon.com/contact-us

**Comment by Moo64c** [comment]
Seems fine on my end ? (top menu "about us" -> "contact us" leads to the correct location on dev)
Check both logged in and not.

**Comment by niryariv** [comment]
yes, the problem is only on the http://dev-ibli.gotpantheon.com/content/what-ibli page button

![screen shot 2014-09-21 at 4 44 16 pm](https://cloud.githubusercontent.com/assets/1771/4348629/680067c8-4195-11e4-8163-8a3ed85a2f49.png)

**Comment by niryariv** [comment]
while you're at it, please remove/hide the "our team" button

**Comment by Moo64c** [comment]
Fixed (notice this was a content issue and when moving to live it may need to be fixed again since it's a relative path)

**Comment by Moo64c** [comment]
You should leave this open so we'd check until after the site goes live.

**Comment by niryariv** [comment]
leaving open - and there's also the removing "our team" button part.

**Comment by Moo64c** [comment]
Wasn't aware that was needed - I removed the button now.

**Comment by niryariv** [comment]
done
