### ISSUE TITLE
Get IBLI Page

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#225]
Can the logos be moved up and replace the names of the insurers in type?

Can you also put Takaful on top and APA below?

![get ibli](https://cloud.githubusercontent.com/assets/6724026/4353408/acd948e0-4232-11e4-925e-5eca991378e6.png)

**Comment by niryariv** [comment]
@Moo64c - plz let me know if u have any questions

**Comment by niryariv** [comment]
@bnedavies should we add the new insurers?

**Comment by bnedavies** [comment]
@niryariv yes please add OIC Logo.  I will send contact details later today

**Comment by bnedavies** [comment]
Megerssa Miressa Dinsa, +251 911 96 63 48

**Comment by niryariv** [comment]
handling in #235 - closing this issue
