### ISSUE TITLE
Partners page - Missing logos

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#227]
please add - 

World Vision - sent before, please let me know if you don't have
APA  - sent before, please let me know if you don't have
Kenya Markets Trust  - sent before, please let me know if you don't have

NEW
USAID - http://www.usaid.gov/branding/web-graphics

**Comment by niryariv** [comment]
@bnedavies I can't find the first World Vision / Kenya Markets Trust - could you please resend?

@nader77 the APA logo is in [Get IBLI page](http://dev-ibli.gotpantheon.com/content/get-ibli)

**Comment by bnedavies** [comment]
Bryn Davies  | Market and Capacity Development Manager
International Livestock Research Institute | ilri.orghttp://www.ilri.org/
Box 30709, Nairobi, Kenya
Tel: +254 20 422 3496  | Skype: bryn.saxe
Email:  b.davies@cgiar.orgmailto:b.davies@cgiar.org

IBLI ONLINE: http://livestockinsurance.wordpress.com/

[Description: cid:image017.png@01CF977E.D0EA1930]
ILRI is a member of the CGIAR Consortiumhttp://www.cgiar.org/

The content of this email may be privileged or confidential. If you are not the intended recipient, please notify the sender immediately and do not copy, distribute or take action based on this email. Please consider the environment before printing this email.

**Comment by bnedavies** [comment]
![picture1](https://cloud.githubusercontent.com/assets/6724026/4438409/8731dd9a-47ab-11e4-86ec-3824d3d45fc1.jpg)

**Comment by bnedavies** [comment]
@niryariv sending other via email

**Comment by niryariv** [comment]
WorldVision logo:

![wv_logo](https://cloud.githubusercontent.com/assets/1771/4439242/4f8baabe-47b6-11e4-99b6-ada9b724d200.png)

**Comment by niryariv** [comment]
@nader77 - please add WorldVision, Kenya Markets Trust, APA and USAID logos.

**Comment by niryariv** [comment]
@nader77 also, please remove all the placeholders:
![screen shot 2014-09-30 at 11 39 32 am](https://cloud.githubusercontent.com/assets/1771/4455282/50abed24-487d-11e4-94ab-bbcb21c61dbd.png)

**Comment by niryariv** [comment]
done
