### ISSUE TITLE
Past Index Maps - PDF 

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#236]
@niryariv - Anyway to include a few things on the PDF file?
1. The legend?
2. The names of the divisions?

**Comment by niryariv** [comment]
1. handling in #240 (is that what you mean?)
2. Can be added, but will be a bit more complicated - can we move this to 1.1?

**Comment by bnedavies** [comment]
1. Yes, exactly, but with colors too.  Your content is black and white.
2. Well, it'll be hard for someone viewing to tell which division is theirs without the names of the divisions...I think it will be requested next week by others for this version...

**Comment by niryariv** [comment]
1. I thought we'd just color the name, I'm concerned coloring the whole background might create readability issues. What do you think? This is easy to change later, in any case.
2. Absolutely. My concern is just time-wise - the main challenge is getting the division geography right. @apurbashee do you have division shapefiles? If not we can create them based on the unit shapefile and the division/unit table.

**Comment by bnedavies** [comment]
1. That's fine
2. I think you can just pull names from unit shape file?  @apurbashee - is this right?

**Comment by niryariv** [comment]
We have the names, the trickier part is to get the division shape from all the units' shapes. It's not a big deal, just thought perhaps there are already division shapefiles so we can save the time.

**Comment by bnedavies** [comment]
@niryariv sorry, we need the unit names, not division names

**Comment by niryariv** [comment]
ok, assigned to #246. I hope this will be usable, there are a lot of small units.
