### ISSUE TITLE
Subscribe Function on homepage

### ISSUE THREAD

**Issue by bnedavies** [Gizra/IBLI#237]
1. When I add a phone number - it asks for a valid email.  How do we make sure we have the country code too?
2. When I add an email, it doesn't send any sort of confirmation....is this working?
3. How do the admin functions work so I can review who has signed up and from where?

**Comment by niryariv** [comment]
1. No problem. Should we allow only numbers from Kenya / Ethiopia?
2. Can you send me text for the confirmation email?
3. We'll add an admin view for this and document how to use it

**Comment by bnedavies** [comment]
1.  We can allow from anywhere, I guess we should just require a country code?
2. "Thank you for signing up for updates about Index-Based Livestock Insurance (IBLI).  We will be in touch soon."
3. Thank you.

**Comment by niryariv** [comment]
opened a ticket for this at #239. What should we use as the From: email address?

**Comment by bnedavies** [comment]
ibliwebsystem@cgiar.org

**Comment by niryariv** [comment]
ok, closing for #239.
