### ISSUE TITLE
Provide SSH access to the server

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#24]

**Comment by alanorth** [comment]
Update: I'm still waiting on ICT to do the port mapping (External -> Internal).  Sorry!

**Comment by alanorth** [comment]
Ok, today they finally came through with the IP mapping and the server is now accessible from outside ILRI.  I will give you guys access soon.  Bad timing though, as I'm going to be out of town until Sunday (so will probably email you credentials on Monday).

**Comment by niryariv** [comment]
thanks Alan!

**Comment by alanorth** [comment]
Emailing @niryariv and @mbrv with shell access to the server...

**Comment by alanorth** [comment]
Ok, both @niryariv and @mbrv have access to the server now.  The next step is figuring out how to run IDL (#16).
