### ISSUE TITLE
embed videos in the IBLI on the Ground items 

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#241]
- [x] replace the current "More details" hover link with a Play icon:
  ![screen shot 2014-09-30 at 4 48 10 pm](https://cloud.githubusercontent.com/assets/1771/4459099/7b3672f0-48a8-11e4-9ca9-b464c6d2679f.png)
  Icon: http://thenounproject.com/term/play/19281/
- [x] When the icon is clicked, open a modal and play the relevant video:

IBLI in Wajir - https://www.youtube.com/watch?v=Cusa9tTuO2k&feature=youtu.be
IBLI in Marsabit - https://www.youtube.com/watch?v=1-w7iht20nw&feature=youtu.be
IBLI Borana - No video yet
IBLI in Isiolo - http://youtu.be/8v26L8rzguc

**Comment by niryariv** [comment]
@nader77 can you make the videos auto-play when the modal is opened?

**Comment by nedSaf** [comment]
Ya, i will do it on PR #245
