### ISSUE TITLE
change map provider?

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#248]
@bnedavies - the current map we're using is not so attractive. We can get a much nicer map containing the same data from Mapbox: 
![screen shot 2014-10-02 at 3 14 04 pm](https://cloud.githubusercontent.com/assets/1771/4490580/cb812012-4a2d-11e4-9609-4080168b9eb9.png)

That comes with a price, but I thinks the $60/year plan should cover it. What do you think? https://www.mapbox.com/plans/

**Comment by bnedavies** [comment]
@niryariv that's fine.  please proceed with the $60 subscription.

**Comment by niryariv** [comment]
great - can you please create an account at https://www.mapbox.com and send me the username/pass? thanks!

**Comment by bnedavies** [comment]
done

**Comment by niryariv** [comment]
cool. handling in #249. @bnedavies when you get some time could you upgrade us to the Basic plan? It'll require entering credit card info.

**Comment by niryariv** [comment]
closing for #254

**Comment by bnedavies** [comment]
upgraded today!
