### ISSUE TITLE
Create homepage template

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#31]
https://docs.google.com/a/gizra.com/drawings/d/1mL1Y3c-6lY3NAbOXHpG_v8Z5RXt0Bo0ApVrVAYrM6FI/edit

https://docs.google.com/drawings/d/1zKVPr0XZpdgyb9_xGdFMuzsNGCnWYLvEymcv9XRJNws/edit

Wajir images dropbox: https://www.dropbox.com/sh/o3ex18ffeyhtavt/iSPH4j0NDp?n=165012481

Other images here: https://drive.google.com/a/gizra.com/?pli=1&urp=https://drive.google.com/a/gizra.com/?pli%3D1%26auth%3DD#folders/0B7Lzf69iarhdZmNrbEtTRi1FaWs

@bnedavies where does ["homepage continued"](https://docs.google.com/drawings/d/1zKVPr0XZpdgyb9_xGdFMuzsNGCnWYLvEymcv9XRJNws/edit) meant to be displayed? it seems like it might be a bit too busy having both on one page?

**Comment by bnedavies** [comment]
@niryariv I couldn't fit all the information listed on the bootstrap/highland theme on to one page - but if you look at the template versus the two pages I have, they should all fit into highland as it is designed.

**Comment by bricel** [comment]
@NofarGizra  - 
- Create a content type (page) with a simple wysiwyg.
- Migrate.
