### ISSUE TITLE
homepage map

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#34]
Create a Build basic app with angular leaflet.
http://tombatossals.github.io/angular-leaflet-directive/#!/examples/customized-markers

**Comment by niryariv** [comment]
are we using angular on IBLI?

**Comment by bricel** [comment]
yes, for the map

**Comment by bricel** [comment]
@ceoaliongroo - Can you guide @NofarGizra on how to create an angular app from zero with our boiler plate.

Thanks
