### ISSUE TITLE
send GIS boundary information

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#4]

**Comment by niryariv** [comment]
@apurbashee - could you email me the GIS files? i'll take care of converting the format, if needed, and storing on git

**Comment by bnedavies** [comment]
Apurba will send this today

**Comment by apurbashee** [comment]
@niryariv I have just sent you the shape files for Kenya and Ethiopia. You can put them in repo.

**Comment by niryariv** [comment]
done: https://github.com/Gizra/IBLI/tree/master/data/gis - closing
