### ISSUE TITLE
Implement Ethiopian Excel spreadsheet in Matlab

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#6]

**Comment by niryariv** [comment]
@apurbashee @woodardjoshua - I understand this is being worked on now?

**Comment by woodardjoshua** [comment]
We had talked about combining this into model but I don't know that Apurba
has made the decision yet. I can set it up to run as a single model, but
would need to get the shape file with kenya divisions and the analog of
divisiion for Ethiopia, along with the processed NDVI data to investigate
this.

In the meantime should I simply assume we are running kenya and Ethiopia
separately and convert just the Ethiopia contract and  data to process in
matlab? If so, I need a copy of the NDVI csv files the program will call.

**Comment by niryariv** [comment]
@apurbashee - any input?

**Comment by niryariv** [comment]
@apurbashee following our call, are you working with @woodardjoshua on this?

**Comment by niryariv** [comment]
@apurbashee status on this?

**Comment by woodardjoshua** [comment]
I am working on this and should have by weekend.
