### ISSUE TITLE
add content for "contact us" page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#60]
based on the [bootstrap template](http://wrapbootstrap.com/preview/WB05K85MJ). 

under **Our Address**

IBLI Project Development Manager
International Livestock Research Institute (ILRI)
P.O. Box 30709 – 00100, Nairobi – Kenya
Tel: +254-20-422 3000 (SwitchBoard) / 3043 (Direct)
Fax: +254-20-422 3001

under **Map**
the map at https://www.google.com/maps/@-1.27137,36.725557,1605m/data=!3m1!1e3?hl=en

**Comment by mldk-tech** [comment]
You see the new google map in the contact us page.
![map](https://cloud.githubusercontent.com/assets/5812423/3144353/708bf970-ea1f-11e3-9e7b-eb5cfa36e31b.png)
