### ISSUE TITLE
create Gallery

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#61]
1. add link in top nav bar (between "Blog" and "Contact Us")
2. create gallery page based on http://wrapbootstrap.com/preview/WB05K85MJ
3. use images from https://www.dropbox.com/sh/o3ex18ffeyhtavt/iSPH4j0NDp?n=165012481

**Comment by niryariv** [comment]
we'll use the "Gallery Item" template (with carousel) with a few changes:

![screen shot 2014-06-05 at 11 46 41 am](https://cloud.githubusercontent.com/assets/1771/3185073/68143db8-ec8e-11e3-9802-50426ff96618.png)

**Comment by NofarGizra** [comment]
This issue is waiting for #102 .

**Comment by bnedavies** [comment]
https://www.flickr.com/photos/125283442@N04/

iblikenya on flickr

**Comment by niryariv** [comment]
@NofarGizra use Flickr - URL above ^

**Comment by niryariv** [comment]
@bnedavies do we want to keep this on the site? perhaps would make sense to put this on a project facebook page?

**Comment by bnedavies** [comment]
@niryariv I kind of like the idea of listing it under "About Us" - Makes IBLI seem more real to see pictures of pastoralists buying IBLI.  Is it a lot of work to link the Gallery to the Flickr account?
