### ISSUE TITLE
fix welcome box

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#62]
1. change "WELCOME MESSAGE" to "WELCOME TO IBLI"
2. add a video element with the AJ video: https://drive.google.com/file/d/0BwyWK0Vut1RBMzQyXzRnbTZ5Yzg/edit?usp=sharing

**Comment by NofarGizra** [comment]
@niryariv 
Please upload the MP4 file to a player service (such as YouTube) so we can implement the video in IBLI content.

**Comment by niryariv** [comment]
@NofarGizra please use this instead for now: https://www.youtube.com/watch?v=wCmqEcvOSwU

**Comment by NofarGizra** [comment]
Dev is updated:

http://dev-ibli.gotpantheon.com/
