### ISSUE TITLE
change footer info

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#64]
- under CONTACT US:

IBLI Project Development Manager
International Livestock Research Institute (ILRI)
P.O. Box 30709 – 00100, Nairobi – Kenya
Tel: +254-20-422 3000 (SwitchBoard) / 3043 (Direct)
Fax: +254-20-422 3001
- under GO SOCIAL:

Flickr: https://www.flickr.com/photos/ilri/sets/72157623247974374/
Wordpress: http://livestockinsurance.wordpress.com/

(the rest will come later)
- under SUBSCRIBE:

"Enter your email or mobile phone number to receive updates about IBLI" with a text box, currently disconnected.

**Comment by mldk-tech** [comment]
@niryariv 
We do not have the wordpress Icon.

**Comment by niryariv** [comment]
@DavidGizra 

``` html
<i class="fa fa-wordpress"></i>
```

should provide this - see [here](http://fortawesome.github.io/Font-Awesome/icon/wordpress/)

**Comment by mldk-tech** [comment]
@niryariv 
Yes i know, but the class does not exist.

**Comment by NofarGizra** [comment]
@DavidGizra 
Let's have a follow-up PR to put all footer texts inside `t()`.

**Comment by NofarGizra** [comment]
Update:
@YuriGizra will do the follow-up PR.
