### ISSUE TITLE
need IBLI's social links

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#65]
YouTube, Twitter, Facebook etc..

**Comment by bnedavies** [comment]
email to login for all is iblikenyaethiopia@gmail.com, password will send via email

**Comment by niryariv** [comment]
@bnedavies i just need the links to the IBLI pages in the above social sites

**Comment by bnedavies** [comment]
https://twitter.com/IBLI_Kenya
https://twitter.com/IBLI_Ethiopia
https://www.youtube.com/channel/UCLcdSaDIcb6VHq3GflfQL0w

I owe you facebook still, we haven't published the page yet, but will do so next week

**Comment by bnedavies** [comment]
facebook: https://www.facebook.com/pages/Index-Based-Livestock-Insurance-Kenya-and-Ethiopia/1408317826105114
