### ISSUE TITLE
create mailchimp account

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#66]
@bnedavies could you create an account at http://mailchimp.com/ and send us the login info? we'll use this for the email newsletters

**Comment by alanorth** [comment]
Psssst, @bnedavies can you change the password and email it to Nir on gmail? :)

**Comment by niryariv** [comment]
@bnedavies the user/pass you sent me on email don't seem to work - could you check again please?

**Comment by mldk-tech** [comment]
You can see that i create the mailchimp list and u can see it in your Drupal site.

![ibli mailchimp](https://cloud.githubusercontent.com/assets/5812423/3189600/8a8d80ac-ecc5-11e3-808b-6620711ef212.png)
![lists _mailchimp](https://cloud.githubusercontent.com/assets/5812423/3189601/8d44b662-ecc5-11e3-86ea-6771fee4bc68.png)
