### ISSUE TITLE
upload video to youtube

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#69]
We need to upload the [AJ video](https://drive.google.com/file/d/0BwyWK0Vut1RBMzQyXzRnbTZ5Yzg/edit?usp=sharing) to YouTube (or Vimeo etc). Is there an IBLI YouTube account?

**Comment by bnedavies** [comment]
iblikenyaethiopia@gmail.com is the email used for youtube login.  will send password via email :)

**Comment by niryariv** [comment]
uploaded: http://youtu.be/Ww88kQP2p4s
