### ISSUE TITLE
Output Matlab results in CSV [was: Provide sample of Matlab outputs for Kenya]

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#7]

**Comment by bnedavies** [comment]
Apurba will send this today

**Comment by apurbashee** [comment]
@niryariv I emailed you a couple of sample Matlab output files..

**Comment by niryariv** [comment]
Thanks, got the files. 

We'll need this in CSV format so we can import to the web platform. From a quick search it seems like Matlab has a [csvwrite()](http://www.mathworks.com/help/matlab/ref/csvwrite.html) feature which takes care of this. Could you look into this?

**Comment by bnedavies** [comment]
@apurbashee this is urgent for Nir to process - how quickly can he have this?

**Comment by apurbashee** [comment]
@niryariv sorry for the delay.. but please give me few more days to get back to you on this.

**Comment by bnedavies** [comment]
@apurbashee we really need this - things are getting delayed...please help!

**Comment by niryariv** [comment]
this is continued in #26 - closing
