### ISSUE TITLE
reimpelement maxBounds on the HP map

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#70]
seems like we had max bounds working well, but after today's update they're gone - please reinstate.

**Comment by niryariv** [comment]
needs advice from @ceoaliongroo

**Comment by ceoaliongroo** [comment]
https://github.com/tombatossals/angular-leaflet-directive/blob/master/doc/maxbounds-attribute.md

@NofarGizra  Add this values in the map configuration

``` javascript
        maxbounds: {
          southWest:{
            lat: -2.3613917533090936,
            lng: 31.662597656249996
          },
          northEast:{
            lat: 3.984820817420321,
            lng: 44.703369140625
          }
        }
```

add maxbounds to the map

``` html
<leaflet center="kenya" defaults="defaults" tiles="tiles" geojson="geojson" controls="controls" legend="legend" maxbounds="maxbounds"></leaflet>
```

cc: @niryariv
