### ISSUE TITLE
updates section

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#71]
![screen shot 2014-05-28 at 2 05 10 pm](https://cloud.githubusercontent.com/assets/1771/3103534/fc784392-e657-11e3-869a-f489f7e11712.png)
- [x] replace "LAST UPDATES" with "LATEST IBLI UPDATES"
- [ ] "News" tab will feature items entered by admin
- [ ] "Events" tab will feature upcoming events from IBLI calendar (@bnedavies  - please provide us with URL for the calendar - could be Google Calendar)
- [x] "Partners" tab will feature the following logos:

![eu](https://cloud.githubusercontent.com/assets/1771/3103587/0f5160ce-e659-11e3-9e84-e61f5d13599f.png)
![ukaid](https://cloud.githubusercontent.com/assets/1771/3103588/0f5402ac-e659-11e3-9494-384f5415a886.png)
![aus_aid](https://cloud.githubusercontent.com/assets/1771/3103589/0f58fb90-e659-11e3-900b-de8dbbda9b18.png)
![takaful](https://cloud.githubusercontent.com/assets/1771/3103590/0f5c34cc-e659-11e3-85bb-63e339bfe2d8.png)
![mercy_corps](https://cloud.githubusercontent.com/assets/1771/3103591/0f6358f6-e659-11e3-82bc-10d8a6d06843.png)

**Comment by mldk-tech** [comment]
You see the last ibli updates plugin.

![ibli last update](https://cloud.githubusercontent.com/assets/5812423/3141891/2c75715c-e99e-11e3-8139-d7139ed205df.png)

**Comment by niryariv** [comment]
@DavidGizra just show the partners logos as a list, no text needed

**Comment by mldk-tech** [comment]
![ibli last update](https://cloud.githubusercontent.com/assets/5812423/3142063/63f10394-e9a8-11e3-99cb-36c0e81a83a7.png)
