### ISSUE TITLE
upload reports in the reports folder

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#73]
please place all the PDF reports that will be linked to in the Reports page [here](https://drive.google.com/a/gizra.com/folderview?id=0B7Lzf69iarhdWlBIMlYwVW5sWEU&usp=sharing)

**Comment by niryariv** [comment]
@bnedavies we decided these will be linked from the blog instead, IIRC?

**Comment by bnedavies** [comment]
@niryariv yes, the blog will have all reports and we've removed from the webplatform.  You can close this.
