### ISSUE TITLE
Icons in Firefox

### ISSUE THREAD

**Issue by NofarGizra** [Gizra/IBLI#77]
Most icons, such as the follow-us icons and the yellow 5-stars, are actually a font.
The font looks good in Chrome, but does not work in Firefox (I haven't checked in other browsers).
So we can either make the font work in all browsers by adding more font files, or we can replace the icons-font with image icons.

**Comment by niryariv** [comment]
it's using [Font Awesome](http://fortawesome.github.io/Font-Awesome/) - it's pretty popular and cross browser, so the issue is probably on our side. 

it's not a big deal in any case (we don't need the star icons and dont have the links for the social icons anyway) so let's put this aside for now

**Comment by mldk-tech** [comment]
Done
