### ISSUE TITLE
convert shapefiles to geoJSON

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#8]

**Comment by niryariv** [comment]
converted via http://converter.mygeodata.eu/vector for testing - might be all that's needed, since this isn't a frequent operation. GeoJSON looks ok:

http://geojson.io/#id=gist:anonymous/3b89cf55e3141b121117&map=7/2.285/37.727

**Comment by alanorth** [comment]
Looks pretty good, @niryariv.  Good to see the shape files are what we thought they were!
