### ISSUE TITLE
when hovering on a division, set opacity to 0.3

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#84]
![screen shot 2014-06-01 at 6 28 46 pm](https://cloud.githubusercontent.com/assets/1771/3141941/85d631de-e9a1-11e3-8d90-bf86aef67a6a.png)

**Comment by NofarGizra** [comment]
Done.
(No PR here because it is done within the IBLI-map project)

**Comment by NofarGizra** [comment]
![ibli map03](https://cloud.githubusercontent.com/assets/3273122/3213986/c0bc1676-efa3-11e3-880e-64fe5f358ce8.png)
