### ISSUE TITLE
provide content & select basic theme for the website

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#9]
we could start with a theme from https://wrapbootstrap.com/

**Comment by bnedavies** [comment]
@niryariv  I think everyone likes this template - http://wrapbootstrap.com/preview/WB05K85MJ - Highland - Multipage Business Template.

I also like this one for the admin functions - http://wrapbootstrap.com/preview/WB0B30DGR - 
Ace - Responsive Admin Template.

Now, as I understand it, I need to start organizing the content to fit the highland template?  Will email a rough outline, but I can start doing some story boarding next week.

Bryn

**Comment by bnedavies** [comment]
@niryariv 
http://cgspace.cgiar.org/handle/10568/21794 - Use this for colors for webplatform
http://ilri-comms.wikispaces.com/ILRI+Logo - Use this for logos for webplatform
