### ISSUE TITLE
remove "action..." in the boxes under map

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#96]
it's fine the box doesn't stretch at all, and just changed color on hover.

![screen shot 2014-06-05 at 11 59 59 am](https://cloud.githubusercontent.com/assets/1771/3185180/e98da860-ec8f-11e3-9ab1-22606b929948.png)

**Comment by niryariv** [comment]
on second thought, please remove the whole stretch effect - just leave the box in the same size, same format, with blue background on hover

**Comment by NofarGizra** [comment]
@DavidGizra 
- Remove the "Action..." links from boxes.
- Do not change CSS on hover.
