### ISSUE TITLE
add contact form to the "Contact Us" page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#97]
based on http://7.pdvop2sz.z8.ru/highland/1.4/contact.html - remove the "upload file" link.

will update here with the IBLI contact email.

**Comment by niryariv** [comment]
marked "done on dev" but no form on the page: http://dev-ibli.gotpantheon.com/contact-us

**Comment by Moo64c** [comment]
@niryariv I see the form (almost the same with some CSS changes) on local in the master branch.
I can't check dev to see if it's there or not (don't have the password). 
Notice it uses the site-wide contact form so it probably sends the contact us emails to the admin account email.

**Comment by niryariv** [comment]
@Moo64c sent u dev pass

**Comment by Moo64c** [comment]
@niryariv it seems the dev site isn't updated to the latest commit in the master branch.
I need access from pantheon's dashboard to update it, or you/Amitai/Brice could do it.
