### ISSUE TITLE
IBLI contact email

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#98]
the Contact Us form will send the inquiries directly to an IBLI contact email - what email address should we use?

**Comment by bnedavies** [comment]
Is it possible to list two?  b.davies@cgiar.org & iblikenyaethiopia@gmail.com?

**Comment by niryariv** [comment]
from our experience, the best method is to have a generic email like contact@ibli.com and then have it forward to any address you like (at some point you may hire someone to handle it and would want the mails going directly to them etc)

**Comment by bnedavies** [comment]
contactibli@cgiar.org

**Comment by niryariv** [comment]
@NofarGizra please have the contact form send the info to contactibli@cgiar.org
